#:kivy 1.1.0

<MainUI>:
    orientation: "vertical"
    rpm: app.info
    Label:
        id:rpm
        text: root.rpm + " RPM"
        center_x:root.width * 1/2
        center_y:root.height * 1/2
#        on_press:app.tr2

    Button:
        id:bu1
        text: "attempt connection"
        center_x:root.width * 3/4
        center_y:root.height * 1/8


    Button:
        id: bu2
        text: "this is button 2"
        center_x:root.width * 1/4
        center_y:root.height * 1/8


    Label:
        id: la1
        text: "this is label 1"
        center_x:root.width * 1/3
        center_y:root.height * 6/8
        
    Label:
        id: la2
        text: "this is label 2"
        center_x:root.width * 2/3
        center_y:root.height * 6/8